// <auto-generated />
using System;
using AJFIlfov.DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AJFIlfov.DataAccess.Migrations
{
    [DbContext(typeof(AjfilfovContext))]
    partial class AjfilfovContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Disponibilitate", b =>
                {
                    b.Property<Guid>("IdDisponibilitate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUtilizator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OraIncepere")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OraIncheiere")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Zi")
                        .HasColumnType("date");

                    b.HasKey("IdDisponibilitate")
                        .HasName("PK__Disponib__A79EDADBA5F65FC0");

                    b.HasIndex("IdUtilizator");

                    b.ToTable("Disponibilitate", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Echipe", b =>
                {
                    b.Property<Guid>("IdEchipa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEchipa")
                        .HasName("PK__Echipe__D4A3A318683D43A3");

                    b.ToTable("Echipe", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Grupe", b =>
                {
                    b.Property<Guid>("IdGrupa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGrupa")
                        .HasName("PK__Grupe__303F6F275E4C9D6A");

                    b.ToTable("Grupe", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.GrupeEchipa", b =>
                {
                    b.Property<Guid>("IdGrupaEchipa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEchipa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGrupa")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdGrupaEchipa")
                        .HasName("PK__GrupeEch__F01D7F8F07F92D34");

                    b.HasIndex("IdEchipa");

                    b.HasIndex("IdGrupa");

                    b.ToTable("GrupeEchipa", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Localitati", b =>
                {
                    b.Property<Guid>("IdLocalitate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLocalitate")
                        .HasName("PK__Localita__937B022C50107212");

                    b.ToTable("Localitati", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Marimi", b =>
                {
                    b.Property<int>("IdMarime")
                        .HasColumnType("int");

                    b.Property<string>("Marime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Tip")
                        .HasColumnType("int");

                    b.HasKey("IdMarime")
                        .HasName("PK__Marimi__95BA145B80EFB053");

                    b.ToTable("Marimi", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Meciuri", b =>
                {
                    b.Property<Guid>("IdMeci")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataJoc")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdArbitru")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdArbitruAsistent1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdArbitruAsistent2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdArbitruRezerva")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEchipaGazda")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdEchipaOaspete")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdObservator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStadionLocalitate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observatii")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("Raport")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Rezultat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMeci")
                        .HasName("PK__Meciuri__4D7C0B75D32C1A8D");

                    b.HasIndex("IdArbitru");

                    b.HasIndex("IdArbitruAsistent1");

                    b.HasIndex("IdArbitruAsistent2");

                    b.HasIndex("IdArbitruRezerva");

                    b.HasIndex("IdEchipaGazda");

                    b.HasIndex("IdEchipaOaspete");

                    b.HasIndex("IdObservator");

                    b.HasIndex("IdStadionLocalitate");

                    b.ToTable("Meciuri", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Refereestat", b =>
                {
                    b.Property<int?>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<int?>("VarstaMedie")
                        .HasColumnType("int")
                        .HasColumnName("varsta_medie");

                    b.ToTable("refereestats", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Roluri", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roluri__2A49584C6CB95133");

                    b.ToTable("Roluri", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Stadioane", b =>
                {
                    b.Property<Guid>("IdStadion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStadion")
                        .HasName("PK__Stadioan__6A3F1A8882EFD894");

                    b.ToTable("Stadioane", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.StadionLocalitate", b =>
                {
                    b.Property<Guid>("IdStadionLocalitate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLocalitate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStadion")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdStadionLocalitate")
                        .HasName("PK__StadionL__8D363E8182F8F13E");

                    b.HasIndex("IdLocalitate");

                    b.HasIndex("IdStadion");

                    b.ToTable("StadionLocalitate", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Utilizatori", b =>
                {
                    b.Property<Guid>("IdUtilizator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DataIncepere")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataNastere")
                        .HasColumnType("date");

                    b.Property<int?>("IdMarimeAdidasi")
                        .HasColumnType("int");

                    b.Property<int?>("IdMarimeHaine")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Parola")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUtilizator")
                        .HasName("PK__Utilizat__99101D6D186B6C92");

                    b.HasIndex("IdMarimeAdidasi");

                    b.HasIndex("IdMarimeHaine");

                    b.HasIndex("IdRol");

                    b.ToTable("Utilizatori", (string)null);
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Disponibilitate", b =>
                {
                    b.HasOne("AJFIlfov.DataAccess.Models.Utilizatori", "IdUtilizatorNavigation")
                        .WithMany("Disponibilitates")
                        .HasForeignKey("IdUtilizator")
                        .HasConstraintName("FK__Disponibi__IdUti__38996AB5");

                    b.Navigation("IdUtilizatorNavigation");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.GrupeEchipa", b =>
                {
                    b.HasOne("AJFIlfov.DataAccess.Models.Echipe", "IdEchipaNavigation")
                        .WithMany("GrupeEchipas")
                        .HasForeignKey("IdEchipa")
                        .HasConstraintName("FK__GrupeEchi__IdEch__2A4B4B5E");

                    b.HasOne("AJFIlfov.DataAccess.Models.Grupe", "IdGrupaNavigation")
                        .WithMany("GrupeEchipas")
                        .HasForeignKey("IdGrupa")
                        .HasConstraintName("FK__GrupeEchi__IdGru__2B3F6F97");

                    b.Navigation("IdEchipaNavigation");

                    b.Navigation("IdGrupaNavigation");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Meciuri", b =>
                {
                    b.HasOne("AJFIlfov.DataAccess.Models.Utilizatori", "IdArbitruNavigation")
                        .WithMany("MeciuriIdArbitruNavigations")
                        .HasForeignKey("IdArbitru")
                        .HasConstraintName("FK__Meciuri__IdArbit__4222D4EF");

                    b.HasOne("AJFIlfov.DataAccess.Models.Utilizatori", "IdArbitruAsistent1Navigation")
                        .WithMany("MeciuriIdArbitruAsistent1Navigations")
                        .HasForeignKey("IdArbitruAsistent1")
                        .HasConstraintName("FK__Meciuri__IdArbit__4316F928");

                    b.HasOne("AJFIlfov.DataAccess.Models.Utilizatori", "IdArbitruAsistent2Navigation")
                        .WithMany("MeciuriIdArbitruAsistent2Navigations")
                        .HasForeignKey("IdArbitruAsistent2")
                        .HasConstraintName("FK__Meciuri__IdArbit__440B1D61");

                    b.HasOne("AJFIlfov.DataAccess.Models.Utilizatori", "IdArbitruRezervaNavigation")
                        .WithMany("MeciuriIdArbitruRezervaNavigations")
                        .HasForeignKey("IdArbitruRezerva")
                        .HasConstraintName("FK__Meciuri__IdArbit__44FF419A");

                    b.HasOne("AJFIlfov.DataAccess.Models.GrupeEchipa", "IdEchipaGazdaNavigation")
                        .WithMany("MeciuriIdEchipaGazdaNavigations")
                        .HasForeignKey("IdEchipaGazda")
                        .HasConstraintName("FK__Meciuri__IdEchip__403A8C7D");

                    b.HasOne("AJFIlfov.DataAccess.Models.GrupeEchipa", "IdEchipaOaspeteNavigation")
                        .WithMany("MeciuriIdEchipaOaspeteNavigations")
                        .HasForeignKey("IdEchipaOaspete")
                        .HasConstraintName("FK__Meciuri__IdEchip__412EB0B6");

                    b.HasOne("AJFIlfov.DataAccess.Models.Utilizatori", "IdObservatorNavigation")
                        .WithMany("MeciuriIdObservatorNavigations")
                        .HasForeignKey("IdObservator")
                        .HasConstraintName("FK__Meciuri__IdObser__45F365D3");

                    b.HasOne("AJFIlfov.DataAccess.Models.StadionLocalitate", "IdStadionLocalitateNavigation")
                        .WithMany("Meciuris")
                        .HasForeignKey("IdStadionLocalitate")
                        .HasConstraintName("FK__Meciuri__IdStadi__46E78A0C");

                    b.Navigation("IdArbitruAsistent1Navigation");

                    b.Navigation("IdArbitruAsistent2Navigation");

                    b.Navigation("IdArbitruNavigation");

                    b.Navigation("IdArbitruRezervaNavigation");

                    b.Navigation("IdEchipaGazdaNavigation");

                    b.Navigation("IdEchipaOaspeteNavigation");

                    b.Navigation("IdObservatorNavigation");

                    b.Navigation("IdStadionLocalitateNavigation");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.StadionLocalitate", b =>
                {
                    b.HasOne("AJFIlfov.DataAccess.Models.Localitati", "IdLocalitateNavigation")
                        .WithMany("StadionLocalitates")
                        .HasForeignKey("IdLocalitate")
                        .HasConstraintName("FK__StadionLo__IdLoc__3C69FB99");

                    b.HasOne("AJFIlfov.DataAccess.Models.Stadioane", "IdStadionNavigation")
                        .WithMany("StadionLocalitates")
                        .HasForeignKey("IdStadion")
                        .HasConstraintName("FK__StadionLo__IdSta__3B75D760");

                    b.Navigation("IdLocalitateNavigation");

                    b.Navigation("IdStadionNavigation");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Utilizatori", b =>
                {
                    b.HasOne("AJFIlfov.DataAccess.Models.Marimi", "IdMarimeAdidasiNavigation")
                        .WithMany("UtilizatoriIdMarimeAdidasiNavigations")
                        .HasForeignKey("IdMarimeAdidasi")
                        .HasConstraintName("FK__Utilizato__IdMar__34C8D9D1");

                    b.HasOne("AJFIlfov.DataAccess.Models.Marimi", "IdMarimeHaineNavigation")
                        .WithMany("UtilizatoriIdMarimeHaineNavigations")
                        .HasForeignKey("IdMarimeHaine")
                        .HasConstraintName("FK__Utilizato__IdMar__35BCFE0A");

                    b.HasOne("AJFIlfov.DataAccess.Models.Roluri", "IdRolNavigation")
                        .WithMany("Utilizatoris")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Utilizato__IdRol__33D4B598");

                    b.Navigation("IdMarimeAdidasiNavigation");

                    b.Navigation("IdMarimeHaineNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Echipe", b =>
                {
                    b.Navigation("GrupeEchipas");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Grupe", b =>
                {
                    b.Navigation("GrupeEchipas");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.GrupeEchipa", b =>
                {
                    b.Navigation("MeciuriIdEchipaGazdaNavigations");

                    b.Navigation("MeciuriIdEchipaOaspeteNavigations");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Localitati", b =>
                {
                    b.Navigation("StadionLocalitates");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Marimi", b =>
                {
                    b.Navigation("UtilizatoriIdMarimeAdidasiNavigations");

                    b.Navigation("UtilizatoriIdMarimeHaineNavigations");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Roluri", b =>
                {
                    b.Navigation("Utilizatoris");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Stadioane", b =>
                {
                    b.Navigation("StadionLocalitates");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.StadionLocalitate", b =>
                {
                    b.Navigation("Meciuris");
                });

            modelBuilder.Entity("AJFIlfov.DataAccess.Models.Utilizatori", b =>
                {
                    b.Navigation("Disponibilitates");

                    b.Navigation("MeciuriIdArbitruAsistent1Navigations");

                    b.Navigation("MeciuriIdArbitruAsistent2Navigations");

                    b.Navigation("MeciuriIdArbitruNavigations");

                    b.Navigation("MeciuriIdArbitruRezervaNavigations");

                    b.Navigation("MeciuriIdObservatorNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
